return {
    diagnostics = {
        error = "",
        warn = "",
        hint = "",
        info = "",
    },
    git = {
        added = "",
        modified = "",
        removed = "",
        renamed = "➜",
        untracked = "",
        ignored = "",
        unstaged = "U",
        staged = "",
        conflict = "",
    },
    gitsigns = {
        add = "┃",
        change = "┋",
        delete = "",
        topdelhfe = "",
        changedelete = "┃",
        untracked = "┃",
    },
    kinds = {
        Array = " ",
        Boolean = " ",
        Class = " ",
        Color = " ",
        Constant = " ",
        Constructor = " ",
        Copilot = " ",
        Enum = " ",
        EnumMember = " ",
        Event = " ",
        Field = " ",
        File = " ",
        Folder = " ",
        Function = " ",
        Interface = " ",
        Key = " ",
        Keyword = " ",
        Macro = "",
        Method = " ",
        Module = " ",
        Namespace = " ",
        Null = " ",
        Number = " ",
        Object = " ",
        Operator = " ",
        Package = " ",
        Property = " ",
        Reference = " ",
        Snippet = " ",
        String = " ",
        Struct = " ",
        Text = " ",
        TypeParameter = " ",
        Unit = " ",
        Value = " ",
        Variable = " ",
    },
    ui = {
        Pencil = "✎",
        Bug = "",
    },
}

